name: APK

on:
  push:
      tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" \
            | base64 --decode > $RUNNER_TEMP/release.keystore


      - name: Build Release APK
        env:
          KEYSTORE: ${{ runner.temp }}/release.keystore
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v6
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error


  publish-github-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
          fetch-tags: true
          ref: apk-build
        
      - name: Download APK artifact
        uses: actions/download-artifact@v7
        with:
          name: apk-release
          path: app/build/outputs/apk/release

      - name: Get version name
        id: get_version
        run: |
          VERSION_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Set TAG env var
        run: |
          RAW=$(git describe --tags --always --abbrev=0 2>/dev/null || echo "${{ github.event.repository.name }}")
          # CLEAN=$(echo "$RAW" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "TAG=$RAW" >> $GITHUB_ENV
          echo "raw=$RAW" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          # draft: false
          # prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: false
          make_latest: true

